### ISSUE TITLE
OSError: [Errno -9999] Unanticipated host error_

### ISSUE THREAD

**Issue by techsetonyoutube** [techsetonyoutube/Jarvis-AI#1]
**We got this Error:**

_Traceback (most recent call last):
  File "/media/pi/TRAVELDRIVE/Jarvis(10.0).py", line 172, in <module>
    with m as source: r.adjust_for_ambient_noise(source)
  File "/usr/local/lib/python3.4/dist-packages/speech_recognition/__init__.py", line 140, in __enter__
    input=True,  # stream is an input stream
  File "/usr/local/lib/python3.4/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9999] Unanticipated host error_

**Comment by techsetonyoutube** [comment]
If anyone can help with this error that would be great, me and @Richard Aspden have been working on jarvis and may be open to new additions to our team!

**Comment by Akul2010** [comment]
maybe switch to using another stt engine, like vosk, whisper, pocketsphinx, etc. speech_recognition's google api is no longer supported.
